OMC2016/Models/Tools/Menubar.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

OMC2016/Controllers/AdministratorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OMC2016.Models.Tools;
using OMC2016.Filters;
using System.Transactions;

namespace OMC2016.Controllers
{
    public class AdministratorController : Controller
    {
        private ApplicationConfig model = new ApplicationConfig();
        // GET: Administrator
        public ActionResult Config()
        {
            Tools.ctlMaster.Instance.GetConnectionString(model);
            return View(model);
        }

        [HttpParamAction]
        public ActionResult Next(ApplicationConfig _Model)
        {
            TempData["message"] = "Comeback";

            return View("Config", _Model);
        }

        [HttpParamAction]
        public ActionResult Publish(ApplicationConfig _Model)
        {
            using (TransactionScope scope = new TransactionScope())
            {
                try
                {
                    Tools.ctlMaster.Instance.UpdateConnectionString(_Model);
                    scope.Complete();
                    ModelState.AddModelError("", "บันทึกเรียบร้อย");
                }
                catch (Exception ex)
                {
                    scope.Dispose();
                    //ModelState.AddModelError("", "บันทึกข้อมูลไม่สำเร็จ");
                    ModelState.AddModelError("", ex.ToString());
                }
            }
            return View("Config", _Model);
        }
    }
}

OMC2016/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OMC2016.Models.Tools;
using System.Threading.Tasks;
using System.Collections;

namespace OMC2016.Controllers
{
    public class MenuController : Controller
    {
        // GET: Menu
        public ActionResult Index()
        {
            using (MenubarDAL DB_Menu = new MenubarDAL())
            {
                return PartialView("_Menubar", DB_Menu.MenuBarItems.ToList());
            }           
        }
    }
}

OMC2016/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@ViewBag.Title - OMC2016</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <style>
        .modal-content {
            width: 600px !important;
            margin: 30px auto !important;
        }
    </style>

    <!-- DataTables CSS -->
    <link href="@Url.Content("~/Content/DataTables/css/dataTables.bootstrap.css")" rel="stylesheet" type="text/css" />
    <!-- DataTables Responsive CSS -->
    <link href="@Url.Content("~/Content/DataTables/css/responsive.dataTables.css")" rel="stylesheet" type="text/css" />

    <link href="@Url.Content("~/Content/morrisjs/morris.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/font-awesome.min.css")" rel="stylesheet" type="text/css" />

    <!-- jQuery -->
    @Scripts.Render("~/bundles/jquery")
    <script src="@Url.Content("~/Scripts/jquery-2.2.4.min.js")"></script>
    @Scripts.Render("~/bundles/bootstrap")
    <script src="@Url.Content("~/Scripts/metisMenu.min.js")"></script>

</head>
<body>
    <!-- /#wrapper -->
    <div id="container">
        <!-- Navigation -->
     @Html.Action("Index", "Menu")

        <div id="page-wrapper">
            <br />
            @RenderBody()
        </div>
        <!-- /#page-wrapper -->

        <div id="modal-container" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-content">
            </div>
        </div>

    </div>

    <!-- DataTables JavaScript -->
    <script src="@Url.Content("~/Scripts/raphael-min.js")"></script>

    <!-- DataTables JavaScript -->
    <script src="@Url.Content("~/Scripts/DataTables/jquery.dataTables.min.js")"></script>
    <script src="@Url.Content("~/Scripts/DataTables/dataTables.bootstrap.min.js")"></script>

    <!-- Custom Theme JavaScript -->
    <script src="@Url.Content("~/Scripts/OMC-Scripts.js")"></script>

    <!--Modal Notification-->
    <script type="text/javascript">
        $(function () {
            // Initialize numeric spinner input boxes
            //$(".numeric-spinner").spinedit();

            // Initalize modal dialog
            // attach modal-container bootstrap attributes to links with .modal-link class.
            // when a link is clicked with these attributes, bootstrap will display the href content in a modal dialog.
            $('body').on('click', '.modal-link', function (e) {
                e.preventDefault();
                $(this).attr('data-target', '#modal-container');
                $(this).attr('data-toggle', 'modal');
            });

            // Attach listener to .modal-close-btn's so that when the button is pressed the modal dialog disappears
            $('body').on('click', '.modal-close-btn', function () {
                $('#modal-container').modal('hide');
            });

            //clear modal cache, so that new content can be loaded
            $('#modal-container').on('hidden.bs.modal', function () {
                $(this).removeData('bs.modal');
            });

            $('#CancelModal').on('click', function () {
                return false;
            });
        });
    </script>


    @RenderSection("scripts", required: false)

</body>
</html>

OMC2016/Views/Shared/_Menubar.cshtml
@model IEnumerable<OMC2016.Models.Tools.MenuBarItem>

@{
    string DepID = string.Empty;
    string PerID = string.Empty;
}

<!-- Navigation -->
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <!-- /.navbar-Top-Left -->
    <div class="navbar-header">
        @Html.ActionLink("Oldmoon Management", "Index", new { controller = "Home" }, new { @class = "navbar-brand" })
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>

    <!-- /.navbar-Top-Right -->
    <ul class="nav navbar-top-links navbar-right">

        <!-- Administrator Menu -->
        @{
            if (Request.Cookies.Get("UserCookie") == null ? true : false)
            {
                PerID = "0";
            }
            else
            {
                PerID = Request.Cookies["UserCookie"]["PerID"];
            }

            if (Request.IsAuthenticated && PerID == "9")
            {
        <li class="dropdown">
            <a class="navbar-Admin dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-tasks fa-fw"></i>  <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-Admin">
                <li>
                    <a href="@Url.Action("Config", "Administrator")"><i class="fa fa-fw fa-cogs"></i> App Configuration</a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="@Url.Action("Test", "Administrator")"><i class="fa fa-fw fa-pencil-square-o"></i> Company Profile</a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#"><i class="fa fa-fw fa-users"></i> Member Control</a>
                </li>
            </ul>
        </li>
            }
        }

        <li class="dropdown">
            <a class="navbar-alerts dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-bell fa-fw"></i>  <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-alerts">
                <li>
                    <a href="#">
                        <div>
                            <i class="fa fa-comment fa-fw"></i> New Comment
                            <span class="pull-right text-muted small">4 minutes ago</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                            <span class="pull-right text-muted small">12 minutes ago</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <i class="fa fa-envelope fa-fw"></i> Message Sent
                            <span class="pull-right text-muted small">4 minutes ago</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <i class="fa fa-tasks fa-fw"></i> New Task
                            <span class="pull-right text-muted small">4 minutes ago</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <i class="fa fa-upload fa-fw"></i> Server Rebooted
                            <span class="pull-right text-muted small">4 minutes ago</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a class="text-center" href="#">
                        <strong>See All Alerts</strong>
                        <i class="fa fa-angle-right"></i>
                    </a>
                </li>
            </ul>
            <!-- /.dropdown-alerts -->
        </li>


        <!-- UserControl -->
        @if (Request.IsAuthenticated)
        {
        <li class="dropdown navbar-login">
            @using (Html.BeginForm("LogOff", "Authentication", FormMethod.Post, new { id = "logoutForm", @class = "form-css" }))
                {
            @Html.AntiForgeryToken()
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> @User.Identity.Name.ToUpper() [D:@Request.Cookies["UserCookie"]["DepID"] | P:@Request.Cookies["UserCookie"]["PerID"]] <b class="caret"></b></a>
            <ul class="dropdown-menu dropdown-login">
                <li>
                    <a href="#"><i class="fa fa-fw fa-user"></i> Profile</a>
                </li>
                <li>
                    @Html.ActionLink(" Settings", "ModalChangePassword", "Authentication",new { id = Request.Cookies["UserCookie"]["UserID"] }, new { @class = "modal-link fa fa-fw fa-gear" })
                </li>
                <li class="divider"></li>
                <li>
                    <a href="javascript:document.getElementById('logoutForm').submit()"><i class="fa fa-fw fa-power-off"></i> Log Out</a>
                </li>
            </ul>
                }
        </li>
        }
        else
        {
            Request.Cookies.Remove("UserCookie");
        <li>@Html.ActionLink("Log in", "Login", "Authentication", routeValues: null, htmlAttributes:  new { id = "loginLink", @class= "login" })</li>
        }
    </ul>

    @{
        if (Request.Cookies.Get("UserCookie") == null ? true : false)
        {
            DepID = "0";
        }
        else
        {
            DepID = Request.Cookies["UserCookie"]["DepID"];
        }
    }
    <!-- End UserControl -->
    <!-- MenuBar -->
    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            @*Level 1*@
            <ul class="nav" id="side-menu">
                @foreach (var item in Model)
                {

                    if (item.MenuIsParrent == false && item.MenuParrentID == 0)
                    {
                        //Dep = ICT Show All Department
                        if (DepID == "15")
                        {
                            if (item.MenuController == null)
                            {
                                <li><a href="#"> <i class="@item.MenuImage"></i> @item.MenuNameOption</a></li>
                            }
                            else
                            {
                                <li><a href="@Url.Action(item.MenuAction, item.MenuController)"><i class="@item.MenuImage"></i> @item.MenuNameOption</a></li>
                            }
                        }
                        //Show My Department
                        else
                        {
                            if (item.MenuDep.ToString() == DepID)
                            {
                                if (item.MenuController == null)
                                {
                                    <li><a href="#"> <i class="@item.MenuImage"></i> @item.MenuNameOption</a></li>
                                }
                                else
                                {
                                    <li><a href="@Url.Action(item.MenuAction, item.MenuController)"><i class="@item.MenuImage"></i> @item.MenuNameOption</a></li>
                                }
                            }
                        }
                    }
                    else
                    {
                        if (item.MenuIsParrent == true && item.MenuParrentID == 0 && DepID != "0")
                        {
                            <li>
                                @*level2*@
                                <a href="#"><i class="@item.MenuImage"></i> @item.MenuNameOption<span class="fa arrow"></span></a>
                                <ul class="nav nav-second-level">
                                    @foreach (var Level2 in Model.Where(p => p.MenuParrentID == item.MenuID).OrderBy(o => o.MenuNameOption))
                                    {
                                        if (DepID == "15")
                                        {
                                            if (Level2.MenuIsParrent == true)
                                            {
                                                <li>
                                                    @*level3*@
                                                    <a href="#">@Level2.MenuNameOption <span class="fa arrow"></span></a>
                                                    <ul class="nav nav-third-level">
                                                        @foreach (var Level3 in Model.Where(p => p.MenuParrentID == Level2.MenuID).OrderBy(o => o.MenuNameOption))
                                                        {
                                                            if (Level3.MenuController == null)
                                                            {
                                                                <li><a href="#">@Level3.MenuNameOption</a></li>
                                                            }
                                                            else
                                                            {
                                                                <li><a href="@Url.Action(Level3.MenuAction, Level3.MenuController)">@Level3.MenuNameOption</a></li>
                                                            }
                                                        }
                                                    </ul>
                                                </li>
                                            }
                                            else
                                            {
                                                if (Level2.MenuController == null)
                                                {
                                                    <li><a href="#">@Level2.MenuNameOption</a></li>
                                                }
                                                else
                                                {
                                                    <li><a href="@Url.Action(Level2.MenuAction, Level2.MenuController)">@Level2.MenuNameOption</a></li>
                                                }
                                            }
                                        }
                                        else if (Level2.MenuParrentID != 0 && Level2.MenuDep.ToString() == DepID || Level2.MenuDep == 0)
                                        {
                                            if (Level2.MenuIsParrent == true)
                                            {
                                                <li>
                                                    @*level3*@
                                                    <a href="#">@Level2.MenuNameOption <span class="fa arrow"></span></a>
                                                    <ul class="nav nav-third-level">
                                                        @foreach (var Level3 in Model.Where(p => p.MenuParrentID == Level2.MenuID).OrderBy(o => o.MenuNameOption))
                                                        {
                                                            if (Level3.MenuController == null)
                                                            {
                                                                <li><a href="#">@Level3.MenuNameOption</a></li>
                                                            }
                                                            else
                                                            {
                                                                <li><a href="@Url.Action(Level3.MenuAction, Level3.MenuController)">@Level3.MenuNameOption</a></li>
                                                            }
                                                        }
                                                    </ul>
                                                </li>
                                            }
                                            else
                                            {
                                                if (Level2.MenuController == null)
                                                {
                                                    <li><a href="#">@Level2.MenuNameOption</a></li>
                                                }
                                                else
                                                {
                                                    <li><a href="@Url.Action(Level2.MenuAction, Level2.MenuController)">@Level2.MenuNameOption</a></li>
                                                }
                                            }
                                        }
                                    }
                                </ul>
                            </li>
                        }
                    }
                }
            </ul>
        </div>
    </div>

    <!-- End MenuBar -->

</nav>